#ifndef SDK_ENUMS_H_
#define SDK_ENUMS_H_

/* NOTE: This file is included from sdk.h and depends on its declarations */
/* clang-format off */

/* Used for CInput.m_pCommands (for crithack) */
#define MULTIPLAYER_BACKUP 90

/*----------------------------------------------------------------------------*/

#define TEAM_RED 2
#define TEAM_BLU 3

#define MAXPLAYERS 100 //+ 1
#define MAXENTITIES 2048 //+ 1

/*----------------------------------------------------------------------------*/

enum {
    CONTENTS_EMPTY                = 0x0,
    CONTENTS_SOLID                = 0x1,
    CONTENTS_WINDOW               = 0x2,
    CONTENTS_AUX                  = 0x4,
    CONTENTS_GRATE                = 0x8,
    CONTENTS_SLIME                = 0x10,
    CONTENTS_WATER                = 0x20,
    CONTENTS_BLOCKLOS             = 0x40,
    CONTENTS_OPAQUE               = 0x80,
    LAST_VISIBLE_CONTENTS         = 0x80,
    ALL_VISIBLE_CONTENTS          = (LAST_VISIBLE_CONTENTS | (LAST_VISIBLE_CONTENTS - 1)),
    CONTENTS_TESTFOGVOLUME        = 0x100,
    CONTENTS_UNUSED               = 0x200,
    CONTENTS_UNUSED6              = 0x400,
    CONTENTS_TEAM1                = 0x800,
    CONTENTS_TEAM2                = 0x1000,
    CONTENTS_IGNORE_NODRAW_OPAQUE = 0x2000,
    CONTENTS_MOVEABLE             = 0x4000,
    CONTENTS_AREAPORTAL           = 0x8000,
    CONTENTS_PLAYERCLIP           = 0x10000,
    CONTENTS_MONSTERCLIP          = 0x20000,
    CONTENTS_CURRENT_0            = 0x40000,
    CONTENTS_CURRENT_90           = 0x80000,
    CONTENTS_CURRENT_180          = 0x100000,
    CONTENTS_CURRENT_270          = 0x200000,
    CONTENTS_CURRENT_UP           = 0x400000,
    CONTENTS_CURRENT_DOWN         = 0x800000,
    CONTENTS_ORIGIN               = 0x1000000,
    CONTENTS_MONSTER              = 0x2000000,
    CONTENTS_DEBRIS               = 0x4000000,
    CONTENTS_DETAIL               = 0x8000000,
    CONTENTS_TRANSLUCENT          = 0x10000000,
    CONTENTS_LADDER               = 0x20000000,
    CONTENTS_HITBOX               = 0x40000000,
};

#define MASK_ALL                   (0xFFFFFFFF)
#define MASK_SOLID                 (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_WINDOW|CONTENTS_MONSTER|CONTENTS_GRATE)
#define MASK_PLAYERSOLID           (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_PLAYERCLIP|CONTENTS_WINDOW|CONTENTS_MONSTER|CONTENTS_GRATE)
#define MASK_NPCSOLID              (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_MONSTERCLIP|CONTENTS_WINDOW|CONTENTS_MONSTER|CONTENTS_GRATE)
#define MASK_WATER                 (CONTENTS_WATER|CONTENTS_MOVEABLE|CONTENTS_SLIME)
#define MASK_OPAQUE                (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_OPAQUE)
#define MASK_OPAQUE_AND_NPCS       (MASK_OPAQUE|CONTENTS_MONSTER)
#define MASK_BLOCKLOS              (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_BLOCKLOS)
#define MASK_BLOCKLOS_AND_NPCS     (MASK_BLOCKLOS|CONTENTS_MONSTER)
#define MASK_VISIBLE               (MASK_OPAQUE|CONTENTS_IGNORE_NODRAW_OPAQUE)
#define MASK_VISIBLE_AND_NPCS      (MASK_OPAQUE_AND_NPCS|CONTENTS_IGNORE_NODRAW_OPAQUE)
#define MASK_SHOT                  (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_MONSTER|CONTENTS_WINDOW|CONTENTS_DEBRIS|CONTENTS_HITBOX)
#define MASK_SHOT_HULL             (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_MONSTER|CONTENTS_WINDOW|CONTENTS_DEBRIS|CONTENTS_GRATE)
#define MASK_SHOT_PORTAL           (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_WINDOW|CONTENTS_MONSTER)
#define MASK_SOLID_BRUSHONLY       (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_WINDOW|CONTENTS_GRATE)
#define MASK_PLAYERSOLID_BRUSHONLY (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_WINDOW|CONTENTS_PLAYERCLIP|CONTENTS_GRATE)
#define MASK_NPCSOLID_BRUSHONLY    (CONTENTS_SOLID|CONTENTS_MOVEABLE|CONTENTS_WINDOW|CONTENTS_MONSTERCLIP|CONTENTS_GRATE)
#define MASK_NPCWORLDSTATIC        (CONTENTS_SOLID|CONTENTS_WINDOW|CONTENTS_MONSTERCLIP|CONTENTS_GRATE)
#define MASK_SPLITAREAPORTAL       (CONTENTS_WATER|CONTENTS_SLIME)
#define MASK_CURRENT               (CONTENTS_CURRENT_0|CONTENTS_CURRENT_90|CONTENTS_CURRENT_180|CONTENTS_CURRENT_270|CONTENTS_CURRENT_UP|CONTENTS_CURRENT_DOWN)
#define MASK_DEADSOLID             (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_WINDOW|CONTENTS_GRATE)
/* clang-format on */

enum TraceType {
    TRACE_EVERYTHING = 0,
    TRACE_WORLD_ONLY,
    TRACE_ENTITIES_ONLY,
    TRACE_EVERYTHING_FILTER_PROPS,
};

/*----------------------------------------------------------------------------*/

enum EFontFlags {
    FONTFLAG_NONE         = 0x000,
    FONTFLAG_ITALIC       = 0x001,
    FONTFLAG_UNDERLINE    = 0x002,
    FONTFLAG_STRIKEOUT    = 0x004,
    FONTFLAG_SYMBOL       = 0x008,
    FONTFLAG_ANTIALIAS    = 0x010,
    FONTFLAG_GAUSSIANBLUR = 0x020,
    FONTFLAG_ROTARY       = 0x040,
    FONTFLAG_DROPSHADOW   = 0x080,
    FONTFLAG_ADDITIVE     = 0x100,
    FONTFLAG_OUTLINE      = 0x200,
    FONTFLAG_CUSTOM       = 0x400,
    FONTFLAG_BITMAP       = 0x800,
};

/* "drawType" argument in ISurface::DrawPrintText */
typedef enum {
    FONT_DRAW_DEFAULT = 0,
    FONT_DRAW_NONADDITIVE,
    FONT_DRAW_ADDITIVE,
    FONT_DRAW_TYPE_COUNT = 2,
} FontDrawType_t;

/* "curStage" argument for IBaseClientDLL::FrameStageNotify */
typedef enum {
    FRAME_UNDEFINED = -1,
    FRAME_START,
    FRAME_NET_UPDATE_START,
    FRAME_NET_UPDATE_POSTDATAUPDATE_START,
    FRAME_NET_UPDATE_POSTDATAUPDATE_END,
    FRAME_NET_UPDATE_END,
    FRAME_RENDER_START,
    FRAME_RENDER_END,
} ClientFrameStage_t;

/* "mode" argument of EngineVGui::Paint */
enum paint_modes {
    PAINT_UIPANELS     = (1 << 0),
    PAINT_INGAMEPANELS = (1 << 1),
    PAINT_CURSOR       = (1 << 2),
};

/*----------------------------------------------------------------------------*/

enum entity_flags {
    FL_ONGROUND              = (1 << 0),
    FL_DUCKING               = (1 << 1),
    FL_WATERJUMP             = (1 << 2),
    FL_ONTRAIN               = (1 << 3),
    FL_INRAIN                = (1 << 4),
    FL_FROZEN                = (1 << 5),
    FL_ATCONTROLS            = (1 << 6),
    FL_CLIENT                = (1 << 7),
    FL_FAKECLIENT            = (1 << 8),
    FL_INWATER               = (1 << 9),
    FL_FLY                   = (1 << 10),
    FL_SWIM                  = (1 << 11),
    FL_CONVEYOR              = (1 << 12),
    FL_NPC                   = (1 << 13),
    FL_GODMODE               = (1 << 14),
    FL_NOTARGET              = (1 << 15),
    FL_AIMTARGET             = (1 << 16),
    FL_PARTIALGROUND         = (1 << 17),
    FL_STATICPROP            = (1 << 18),
    FL_GRAPHED               = (1 << 19),
    FL_GRENADE               = (1 << 20),
    FL_STEPMOVEMENT          = (1 << 21),
    FL_DONTTOUCH             = (1 << 22),
    FL_BASEVELOCITY          = (1 << 23),
    FL_WORLDBRUSH            = (1 << 24),
    FL_OBJECT                = (1 << 25),
    FL_KILLME                = (1 << 26),
    FL_ONFIRE                = (1 << 27),
    FL_DISSOLVING            = (1 << 28),
    FL_TRANSRAGDOLL          = (1 << 29),
    FL_UNBLOCKABLE_BY_PLAYER = (1 << 30)
};

enum MoveType_t {
    MOVETYPE_NONE = 0,
    MOVETYPE_ISOMETRIC,
    MOVETYPE_WALK,
    MOVETYPE_STEP,
    MOVETYPE_FLY,
    MOVETYPE_FLYGRAVITY,
    MOVETYPE_VPHYSICS,
    MOVETYPE_PUSH,
    MOVETYPE_NOCLIP,
    MOVETYPE_LADDER,
    MOVETYPE_OBSERVER,
    MOVETYPE_CUSTOM,

    MOVETYPE_LAST = MOVETYPE_CUSTOM,

    MOVETYPE_MAX_BITS = 4
};

enum EWaterLevels {
    WL_NotInWater = 0,
    WL_Feet,
    WL_Waist,
    WL_Eyes,
};

enum ETFClientClass {
    CClass_CTFWearableRazorback                  = 341,
    CClass_CTFWearableDemoShield                 = 338,
    CClass_CTFWearableLevelableItem              = 340,
    CClass_CTFWearableCampaignItem               = 337,
    CClass_CTFBaseRocket                         = 185,
    CClass_CTFWeaponBaseMerasmusGrenade          = 325,
    CClass_CTFWeaponBaseMelee                    = 324,
    CClass_CTFWeaponBaseGun                      = 323,
    CClass_CTFWeaponBaseGrenadeProj              = 322,
    CClass_CTFWeaponBase                         = 321,
    CClass_CTFWearableRobotArm                   = 342,
    CClass_CTFRobotArm                           = 287,
    CClass_CTFWrench                             = 344,
    CClass_CTFProjectile_ThrowableBreadMonster   = 279,
    CClass_CTFProjectile_ThrowableBrick          = 280,
    CClass_CTFProjectile_ThrowableRepel          = 281,
    CClass_CTFProjectile_Throwable               = 278,
    CClass_CTFThrowable                          = 319,
    CClass_CTFSyringeGun                         = 315,
    CClass_CTFKatana                             = 225,
    CClass_CTFSword                              = 314,
    CClass_CSniperDot                            = 118,
    CClass_CTFSniperRifleClassic                 = 308,
    CClass_CTFSniperRifleDecap                   = 309,
    CClass_CTFSniperRifle                        = 307,
    CClass_CTFChargedSMG                         = 197,
    CClass_CTFSMG                                = 306,
    CClass_CTFSlap                               = 305,
    CClass_CTFShovel                             = 304,
    CClass_CTFShotgunBuildingRescue              = 303,
    CClass_CTFPEPBrawlerBlaster                  = 241,
    CClass_CTFSodaPopper                         = 310,
    CClass_CTFShotgun_Revenge                    = 301,
    CClass_CTFScatterGun                         = 297,
    CClass_CTFShotgun_Pyro                       = 300,
    CClass_CTFShotgun_HWG                        = 299,
    CClass_CTFShotgun_Soldier                    = 302,
    CClass_CTFShotgun                            = 298,
    CClass_CTFRocketPack                         = 296,
    CClass_CTFCrossbow                           = 201,
    CClass_CTFRocketLauncher_Mortar              = 295,
    CClass_CTFRocketLauncher_AirStrike           = 293,
    CClass_CTFRocketLauncher_DirectHit           = 294,
    CClass_CTFRocketLauncher                     = 292,
    CClass_CTFRevolver                           = 286,
    CClass_CTFDRGPomson                          = 202,
    CClass_CTFRaygun                             = 284,
    CClass_CTFPistol_ScoutSecondary              = 246,
    CClass_CTFPistol_ScoutPrimary                = 245,
    CClass_CTFPistol_Scout                       = 244,
    CClass_CTFPistol                             = 243,
    CClass_CTFPipebombLauncher                   = 242,
    CClass_CTFWeaponPDA_Spy                      = 332,
    CClass_CTFWeaponPDA_Engineer_Destroy         = 331,
    CClass_CTFWeaponPDA_Engineer_Build           = 330,
    CClass_CTFWeaponPDAExpansion_Teleporter      = 334,
    CClass_CTFWeaponPDAExpansion_Dispenser       = 333,
    CClass_CTFWeaponPDA                          = 329,
    CClass_CTFParticleCannon                     = 239,
    CClass_CTFParachute_Secondary                = 238,
    CClass_CTFParachute_Primary                  = 237,
    CClass_CTFParachute                          = 236,
    CClass_CTFMinigun                            = 234,
    CClass_CTFMedigunShield                      = 231,
    CClass_CWeaponMedigun                        = 352,
    CClass_CTFProjectile_MechanicalArmOrb        = 263,
    CClass_CTFMechanicalArm                      = 230,
    CClass_CTFLunchBox_Drink                     = 229,
    CClass_CTFLunchBox                           = 228,
    CClass_CLaserDot                             = 78,
    CClass_CTFLaserPointer                       = 227,
    CClass_CTFKnife                              = 226,
    CClass_CTFGasManager                         = 212,
    CClass_CTFProjectile_JarGas                  = 261,
    CClass_CTFJarGas                             = 223,
    CClass_CTFProjectile_Cleaver                 = 254,
    CClass_CTFProjectile_JarMilk                 = 262,
    CClass_CTFProjectile_Jar                     = 260,
    CClass_CTFCleaver                            = 198,
    CClass_CTFJarMilk                            = 224,
    CClass_CTFJar                                = 222,
    CClass_CTFWeaponInvis                        = 328,
    CClass_CTFCannon                             = 196,
    CClass_CTFGrenadeLauncher                    = 216,
    CClass_CTFGrenadePipebombProjectile          = 217,
    CClass_CTFGrapplingHook                      = 215,
    CClass_CTFFlareGun_Revenge                   = 210,
    CClass_CTFFlareGun                           = 209,
    CClass_CTFFlameRocket                        = 207,
    CClass_CTFFlameThrower                       = 208,
    CClass_CTFFists                              = 205,
    CClass_CTFFireAxe                            = 204,
    CClass_CTFWeaponFlameBall                    = 327,
    CClass_CTFCompoundBow                        = 200,
    CClass_CTFClub                               = 199,
    CClass_CTFBuffItem                           = 195,
    CClass_CTFStickBomb                          = 312,
    CClass_CTFBreakableSign                      = 194,
    CClass_CTFBottle                             = 192,
    CClass_CTFBreakableMelee                     = 193,
    CClass_CTFBonesaw                            = 190,
    CClass_CTFBall_Ornament                      = 182,
    CClass_CTFStunBall                           = 313,
    CClass_CTFBat_Giftwrap                       = 188,
    CClass_CTFBat_Wood                           = 189,
    CClass_CTFBat_Fish                           = 187,
    CClass_CTFBat                                = 186,
    CClass_CTFProjectile_EnergyRing              = 256,
    CClass_CTFDroppedWeapon                      = 203, /* !!! */
    CClass_CTFWeaponSapper                       = 335,
    CClass_CTFWeaponBuilder                      = 326,
    CClass_C_TFWeaponBuilder                     = 0,
    CClass_CTFProjectile_Rocket                  = 264,
    CClass_CTFProjectile_Flare                   = 257,
    CClass_CTFProjectile_EnergyBall              = 255,
    CClass_CTFProjectile_GrapplingHook           = 258,
    CClass_CTFProjectile_HealingBolt             = 259,
    CClass_CTFProjectile_Arrow                   = 252,
    CClass_CMannVsMachineStats                   = 80,
    CClass_CTFTankBoss                           = 316,
    CClass_CTFBaseBoss                           = 183,
    CClass_CBossAlpha                            = 0,
    CClass_NextBotCombatCharacter                = 357,
    CClass_CTFProjectile_SpellKartBats           = 268,
    CClass_CTFProjectile_SpellKartOrb            = 269,
    CClass_CTFHellZap                            = 220,
    CClass_CTFProjectile_SpellLightningOrb       = 270,
    CClass_CTFProjectile_SpellTransposeTeleport  = 277,
    CClass_CTFProjectile_SpellMeteorShower       = 271,
    CClass_CTFProjectile_SpellSpawnBoss          = 274,
    CClass_CTFProjectile_SpellMirv               = 272,
    CClass_CTFProjectile_SpellPumpkin            = 273,
    CClass_CTFProjectile_SpellSpawnHorde         = 275,
    CClass_CTFProjectile_SpellSpawnZombie        = 276,
    CClass_CTFProjectile_SpellBats               = 266,
    CClass_CTFProjectile_SpellFireball           = 267,
    CClass_CTFSpellBook                          = 311,
    CClass_CHightower_TeleportVortex             = 74,
    CClass_CTeleportVortex                       = 160,
    CClass_CZombie                               = 354,
    CClass_CMerasmusDancer                       = 83,
    CClass_CMerasmus                             = 82,
    CClass_CHeadlessHatman                       = 73,
    CClass_CEyeballBoss                          = 48,
    CClass_CTFBotHintEngineerNest                = 191,
    CClass_CBotNPCMinion                         = 0,
    CClass_CBotNPC                               = 0,
    CClass_CPasstimeGun                          = 94,
    CClass_CTFViewModel                          = 320,
    CClass_CRobotDispenser                       = 112,
    CClass_CTFRobotDestruction_Robot             = 288,
    CClass_CTFReviveMarker                       = 285,
    CClass_CTFPumpkinBomb                        = 282,
    CClass_CTFProjectile_BallOfFire              = 253,
    CClass_CTFBaseProjectile                     = 184,
    CClass_CTFPointManager                       = 250,
    CClass_CBaseObjectUpgrade                    = 11,
    CClass_CTFRobotDestructionLogic              = 291,
    CClass_CTFRobotDestruction_RobotGroup        = 289,
    CClass_CTFRobotDestruction_RobotSpawn        = 290,
    CClass_CTFPlayerDestructionLogic             = 248,
    CClass_CPlayerDestructionDispenser           = 101,
    CClass_CTFMinigameLogic                      = 233,
    CClass_CTFHalloweenMinigame_FallingPlatforms = 219,
    CClass_CTFHalloweenMinigame                  = 218,
    CClass_CTFMiniGame                           = 232,
    CClass_CTFPowerupBottle                      = 251,
    CClass_CTFItem                               = 221,
    CClass_CHalloweenSoulPack                    = 71,
    CClass_CTFGenericBomb                        = 213,
    CClass_CBonusRoundLogic                      = 23,
    CClass_CTFGameRulesProxy                     = 211,
    CClass_CTETFParticleEffect                   = 179,
    CClass_CTETFExplosion                        = 178,
    CClass_CTETFBlood                            = 177,
    CClass_CTFFlameManager                       = 206,
    CClass_CHalloweenGiftPickup                  = 69,
    CClass_CBonusDuckPickup                      = 21,
    CClass_CHalloweenPickup                      = 70,
    CClass_CCaptureFlagReturnIcon                = 27,
    CClass_CCaptureFlag                          = 26,
    CClass_CBonusPack                            = 22,
    CClass_CTFTeam                               = 318,
    CClass_CTFTauntProp                          = 317,
    CClass_CTFPlayerResource                     = 249,
    CClass_CTFPlayer                             = 247, /* !!! */
    CClass_CTFRagdoll                            = 283,
    CClass_CTEPlayerAnimEvent                    = 165,
    CClass_CTFPasstimeLogic                      = 240,
    CClass_CPasstimeBall                         = 93,
    CClass_CTFObjectiveResource                  = 235,
    CClass_CTFGlow                               = 214,
    CClass_CTEFireBullets                        = 152,
    CClass_CTFBuffBanner                         = 0,
    CClass_CTFAmmoPack                           = 181, /* !!! */
    CClass_CObjectTeleporter                     = 89,  /* !!! */
    CClass_CObjectSentrygun                      = 88,  /* !!! */
    CClass_CTFProjectile_SentryRocket            = 265,
    CClass_CObjectSapper                         = 87,
    CClass_CObjectCartDispenser                  = 85,
    CClass_CObjectDispenser                      = 86, /* !!! */
    CClass_CMonsterResource                      = 84,
    CClass_CFuncRespawnRoomVisualizer            = 64,
    CClass_CFuncRespawnRoom                      = 63,
    CClass_CFuncPasstimeGoal                     = 61,
    CClass_CFuncForceField                       = 57,
    CClass_CCaptureZone                          = 28,
    CClass_CCurrencyPack                         = 31, /* !!! */
    CClass_CBaseObject                           = 10,
    CClass_CTestTraceline                        = 176,
    CClass_CTEWorldDecal                         = 180,
    CClass_CTESpriteSpray                        = 174,
    CClass_CTESprite                             = 173,
    CClass_CTESparks                             = 172,
    CClass_CTESmoke                              = 171,
    CClass_CTEShowLine                           = 169,
    CClass_CTEProjectedDecal                     = 167,
    CClass_CTEPlayerDecal                        = 166,
    CClass_CTEPhysicsProp                        = 164,
    CClass_CTEParticleSystem                     = 163,
    CClass_CTEMuzzleFlash                        = 162,
    CClass_CTELargeFunnel                        = 159,
    CClass_CTEKillPlayerAttachments              = 158,
    CClass_CTEImpact                             = 157,
    CClass_CTEGlowSprite                         = 156,
    CClass_CTEShatterSurface                     = 168,
    CClass_CTEFootprintDecal                     = 154,
    CClass_CTEFizz                               = 153,
    CClass_CTEExplosion                          = 151,
    CClass_CTEEnergySplash                       = 150,
    CClass_CTEEffectDispatch                     = 149,
    CClass_CTEDynamicLight                       = 148,
    CClass_CTEDecal                              = 146,
    CClass_CTEClientProjectile                   = 145,
    CClass_CTEBubbleTrail                        = 144,
    CClass_CTEBubbles                            = 143,
    CClass_CTEBSPDecal                           = 142,
    CClass_CTEBreakModel                         = 141,
    CClass_CTEBloodStream                        = 140,
    CClass_CTEBloodSprite                        = 139,
    CClass_CTEBeamSpline                         = 138,
    CClass_CTEBeamRingPoint                      = 137,
    CClass_CTEBeamRing                           = 136,
    CClass_CTEBeamPoints                         = 135,
    CClass_CTEBeamLaser                          = 134,
    CClass_CTEBeamFollow                         = 133,
    CClass_CTEBeamEnts                           = 132,
    CClass_CTEBeamEntPoint                       = 131,
    CClass_CTEBaseBeam                           = 130,
    CClass_CTEArmorRicochet                      = 129,
    CClass_CTEMetalSparks                        = 161,
    CClass_CSteamJet                             = 123,
    CClass_CSmokeStack                           = 117,
    CClass_DustTrail                             = 355,
    CClass_CFireTrail                            = 50,
    CClass_SporeTrail                            = 362,
    CClass_SporeExplosion                        = 361,
    CClass_RocketTrail                           = 359,
    CClass_SmokeTrail                            = 360,
    CClass_CPropVehicleDriveable                 = 108,
    CClass_ParticleSmokeGrenade                  = 358,
    CClass_CParticleFire                         = 90,
    CClass_MovieExplosion                        = 356,
    CClass_CTEGaussExplosion                     = 155,
    CClass_CEnvQuadraticBeam                     = 43,
    CClass_CEmbers                               = 36,
    CClass_CEnvWind                              = 47,
    CClass_CPrecipitation                        = 107,
    CClass_CBaseTempEntity                       = 17,
    CClass_CWeaponIFMSteadyCam                   = 351,
    CClass_CWeaponIFMBaseCamera                  = 350,
    CClass_CWeaponIFMBase                        = 349,
    CClass_CTFWearableVM                         = 343,
    CClass_CTFWearable                           = 336,
    CClass_CTFWearableItem                       = 339,
    CClass_CEconWearable                         = 35,
    CClass_CBaseAttributableItem                 = 3,
    CClass_CEconEntity                           = 34,
    CClass_CHandleTest                           = 72,
    CClass_CTeamplayRoundBasedRulesProxy         = 126,
    CClass_CTeamRoundTimer                       = 127,
    CClass_CSpriteTrail                          = 122,
    CClass_CSpriteOriented                       = 121,
    CClass_CSprite                               = 120,
    CClass_CRagdollPropAttached                  = 111,
    CClass_CRagdollProp                          = 110,
    CClass_CPoseController                       = 106,
    CClass_CGameRulesProxy                       = 68,
    CClass_CInfoLadderDismount                   = 75,
    CClass_CFuncLadder                           = 58,
    CClass_CEnvDetailController                  = 40,
    CClass_CWorld                                = 353,
    CClass_CWaterLODControl                      = 348,
    CClass_CWaterBullet                          = 347,
    CClass_CVoteController                       = 346,
    CClass_CVGuiScreen                           = 345,
    CClass_CPropJeep                             = 0,
    CClass_CPropVehicleChoreoGeneric             = 0,
    CClass_CTest_ProxyToggle_Networkable         = 175,
    CClass_CTesla                                = 170,
    CClass_CTeamTrainWatcher                     = 128,
    CClass_CBaseTeamObjectiveResource            = 16,
    CClass_CTeam                                 = 125,
    CClass_CSun                                  = 124,
    CClass_CParticlePerformanceMonitor           = 91,
    CClass_CSpotlightEnd                         = 119,
    CClass_CSlideshowDisplay                     = 116,
    CClass_CShadowControl                        = 115,
    CClass_CSceneEntity                          = 114,
    CClass_CRopeKeyframe                         = 113,
    CClass_CRagdollManager                       = 109,
    CClass_CPhysicsPropMultiplayer               = 98,
    CClass_CPhysBoxMultiplayer                   = 96,
    CClass_CBasePropDoor                         = 15,
    CClass_CDynamicProp                          = 33,
    CClass_CPointWorldText                       = 105,
    CClass_CPointCommentaryNode                  = 104,
    CClass_CPointCamera                          = 103,
    CClass_CPlayerResource                       = 102,
    CClass_CPlasma                               = 100,
    CClass_CPhysMagnet                           = 99,
    CClass_CPhysicsProp                          = 97,
    CClass_CPhysBox                              = 95,
    CClass_CParticleSystem                       = 92,
    CClass_CMaterialModifyControl                = 81,
    CClass_CLightGlow                            = 79,
    CClass_CInfoOverlayAccessor                  = 77,
    CClass_CFuncTrackTrain                       = 67,
    CClass_CFuncSmokeVolume                      = 66,
    CClass_CFuncRotating                         = 65,
    CClass_CFuncReflectiveGlass                  = 62,
    CClass_CFuncOccluder                         = 60,
    CClass_CFuncMonitor                          = 59,
    CClass_CFunc_LOD                             = 54,
    CClass_CTEDust                               = 147,
    CClass_CFunc_Dust                            = 53,
    CClass_CFuncConveyor                         = 56,
    CClass_CBreakableSurface                     = 25,
    CClass_CFuncAreaPortalWindow                 = 55,
    CClass_CFish                                 = 51,
    CClass_CEntityFlame                          = 38,
    CClass_CFireSmoke                            = 49,
    CClass_CEnvTonemapController                 = 46,
    CClass_CEnvScreenEffect                      = 44,
    CClass_CEnvScreenOverlay                     = 45,
    CClass_CEnvProjectedTexture                  = 42,
    CClass_CEnvParticleScript                    = 41,
    CClass_CFogController                        = 52,
    CClass_CEntityParticleTrail                  = 39,
    CClass_CEntityDissolve                       = 37,
    CClass_CDynamicLight                         = 32,
    CClass_CColorCorrectionVolume                = 30,
    CClass_CColorCorrection                      = 29,
    CClass_CBreakableProp                        = 24,
    CClass_CBasePlayer                           = 13,
    CClass_CBaseFlex                             = 8,
    CClass_CBaseEntity                           = 7,
    CClass_CBaseDoor                             = 6,
    CClass_CBaseCombatCharacter                  = 4,
    CClass_CBaseAnimatingOverlay                 = 2,
    CClass_CBoneFollower                         = 20,
    CClass_CBaseAnimating                        = 1, /* !!! */
    CClass_CInfoLightingRelative                 = 76,
    CClass_CAI_BaseNPC                           = 0,
    CClass_CBeam                                 = 19,
    CClass_CBaseViewModel                        = 18,
    CClass_CBaseProjectile                       = 14,
    CClass_CBaseParticleEntity                   = 12,
    CClass_CBaseGrenade                          = 9,
    CClass_CBaseCombatWeapon                     = 5
};

enum ETFWeaponType {
    TF_WEAPON_NONE = 0,
    TF_WEAPON_BAT,
    TF_WEAPON_BAT_WOOD,
    TF_WEAPON_BOTTLE,
    TF_WEAPON_FIREAXE,
    TF_WEAPON_CLUB,
    TF_WEAPON_CROWBAR,
    TF_WEAPON_KNIFE,
    TF_WEAPON_FISTS,
    TF_WEAPON_SHOVEL,
    TF_WEAPON_WRENCH,
    TF_WEAPON_BONESAW,
    TF_WEAPON_SHOTGUN_PRIMARY,
    TF_WEAPON_SHOTGUN_SOLDIER,
    TF_WEAPON_SHOTGUN_HWG,
    TF_WEAPON_SHOTGUN_PYRO,
    TF_WEAPON_SCATTERGUN,
    TF_WEAPON_SNIPERRIFLE,
    TF_WEAPON_MINIGUN,
    TF_WEAPON_SMG,
    TF_WEAPON_SYRINGEGUN_MEDIC,
    TF_WEAPON_TRANQ,
    TF_WEAPON_ROCKETLAUNCHER,
    TF_WEAPON_GRENADELAUNCHER,
    TF_WEAPON_PIPEBOMBLAUNCHER,
    TF_WEAPON_FLAMETHROWER,
    TF_WEAPON_GRENADE_NORMAL,
    TF_WEAPON_GRENADE_CONCUSSION,
    TF_WEAPON_GRENADE_NAIL,
    TF_WEAPON_GRENADE_MIRV,
    TF_WEAPON_GRENADE_MIRV_DEMOMAN,
    TF_WEAPON_GRENADE_NAPALM,
    TF_WEAPON_GRENADE_GAS,
    TF_WEAPON_GRENADE_EMP,
    TF_WEAPON_GRENADE_CALTROP,
    TF_WEAPON_GRENADE_PIPEBOMB,
    TF_WEAPON_GRENADE_SMOKE_BOMB,
    TF_WEAPON_GRENADE_HEAL,
    TF_WEAPON_GRENADE_STUNBALL,
    TF_WEAPON_GRENADE_JAR,
    TF_WEAPON_GRENADE_JAR_MILK,
    TF_WEAPON_PISTOL,
    TF_WEAPON_PISTOL_SCOUT,
    TF_WEAPON_REVOLVER,
    TF_WEAPON_NAILGUN,
    TF_WEAPON_PDA,
    TF_WEAPON_PDA_ENGINEER_BUILD,
    TF_WEAPON_PDA_ENGINEER_DESTROY,
    TF_WEAPON_PDA_SPY,
    TF_WEAPON_BUILDER,
    TF_WEAPON_MEDIGUN,
    TF_WEAPON_GRENADE_MIRVBOMB,
    TF_WEAPON_FLAMETHROWER_ROCKET,
    TF_WEAPON_GRENADE_DEMOMAN,
    TF_WEAPON_SENTRY_BULLET,
    TF_WEAPON_SENTRY_ROCKET,
    TF_WEAPON_DISPENSER,
    TF_WEAPON_INVIS,
    TF_WEAPON_FLAREGUN,
    TF_WEAPON_LUNCHBOX,
    TF_WEAPON_JAR,
    TF_WEAPON_COMPOUND_BOW,
    TF_WEAPON_BUFF_ITEM,
    TF_WEAPON_PUMPKIN_BOMB,
    TF_WEAPON_SWORD,
    TF_WEAPON_ROCKETLAUNCHER_DIRECTHIT,
    TF_WEAPON_LIFELINE,
    TF_WEAPON_LASER_POINTER,
    TF_WEAPON_DISPENSER_GUN,
    TF_WEAPON_SENTRY_REVENGE,
    TF_WEAPON_JAR_MILK,
    TF_WEAPON_HANDGUN_SCOUT_PRIMARY,
    TF_WEAPON_BAT_FISH,
    TF_WEAPON_CROSSBOW,
    TF_WEAPON_STICKBOMB,
    TF_WEAPON_HANDGUN_SCOUT_SECONDARY,
    TF_WEAPON_SODA_POPPER,
    TF_WEAPON_SNIPERRIFLE_DECAP,
    TF_WEAPON_RAYGUN,
    TF_WEAPON_PARTICLE_CANNON,
    TF_WEAPON_MECHANICAL_ARM,
    TF_WEAPON_DRG_POMSON,
    TF_WEAPON_BAT_GIFTWRAP,
    TF_WEAPON_GRENADE_ORNAMENT_BALL,
    TF_WEAPON_FLAREGUN_REVENGE,
    TF_WEAPON_PEP_BRAWLER_BLASTER,
    TF_WEAPON_CLEAVER,
    TF_WEAPON_GRENADE_CLEAVER,
    TF_WEAPON_STICKY_BALL_LAUNCHER,
    TF_WEAPON_GRENADE_STICKY_BALL,
    TF_WEAPON_SHOTGUN_BUILDING_RESCUE,
    TF_WEAPON_CANNON,
    TF_WEAPON_THROWABLE,
    TF_WEAPON_GRENADE_THROWABLE,
    TF_WEAPON_PDA_SPY_BUILD,
    TF_WEAPON_GRENADE_WATERBALLOON,
    TF_WEAPON_HARVESTER_SAW,
    TF_WEAPON_SPELLBOOK,
    TF_WEAPON_SPELLBOOK_PROJECTILE,
    TF_WEAPON_SNIPERRIFLE_CLASSIC,
    TF_WEAPON_PARACHUTE,
    TF_WEAPON_GRAPPLINGHOOK,
    TF_WEAPON_PASSTIME_GUN,
    TF_WEAPON_CHARGED_SMG,
    TF_WEAPON_COUNT,
};

enum ETFItemDefIndex {
    Scout_m_Scattergun                                = 13,
    Scout_m_ScattergunR                               = 200,
    Scout_m_ForceANature                              = 45,
    Scout_m_TheShortstop                              = 220,
    Scout_m_TheSodaPopper                             = 448,
    Scout_m_FestiveScattergun                         = 669,
    Scout_m_BabyFacesBlaster                          = 772,
    Scout_m_SilverBotkillerScattergunMkI              = 799,
    Scout_m_GoldBotkillerScattergunMkI                = 808,
    Scout_m_RustBotkillerScattergunMkI                = 888,
    Scout_m_BloodBotkillerScattergunMkI               = 897,
    Scout_m_CarbonadoBotkillerScattergunMkI           = 906,
    Scout_m_DiamondBotkillerScattergunMkI             = 915,
    Scout_m_SilverBotkillerScattergunMkII             = 964,
    Scout_m_GoldBotkillerScattergunMkII               = 973,
    Scout_m_FestiveForceANature                       = 1078,
    Scout_m_TheBackScatter                            = 1103,
    Scout_m_NightTerror                               = 15002,
    Scout_m_TartanTorpedo                             = 15015,
    Scout_m_CountryCrusher                            = 15021,
    Scout_m_BackcountryBlaster                        = 15029,
    Scout_m_SpruceDeuce                               = 15036,
    Scout_m_CurrentEvent                              = 15053,
    Scout_m_MacabreWeb                                = 15065,
    Scout_m_Nutcracker                                = 15069,
    Scout_m_BlueMew                                   = 15106,
    Scout_m_FlowerPower                               = 15107,
    Scout_m_ShottoHell                                = 15108,
    Scout_m_CoffinNail                                = 15131,
    Scout_m_KillerBee                                 = 15151,
    Scout_m_Corsair                                   = 15157,
    Scout_s_ScoutsPistol                              = 23,
    Scout_s_PistolR                                   = 209,
    Scout_s_BonkAtomicPunch                           = 46,
    Scout_s_VintageLugermorph                         = 160,
    Scout_s_CritaCola                                 = 163,
    Scout_s_MadMilk                                   = 222,
    Scout_s_Lugermorph                                = 294,
    Scout_s_TheWinger                                 = 449,
    Scout_s_PrettyBoysPocketPistol                    = 773,
    Scout_s_TheFlyingGuillotine                       = 812,
    Scout_s_TheFlyingGuillotineG                      = 833,
    Scout_s_MutatedMilk                               = 1121,
    Scout_s_FestiveBonk                               = 1145,
    Scout_s_RedRockRoscoe                             = 15013,
    Scout_s_HomemadeHeater                            = 15018,
    Scout_s_HickoryHolepuncher                        = 15035,
    Scout_s_LocalHero                                 = 15041,
    Scout_s_BlackDahlia                               = 15046,
    Scout_s_SandstoneSpecial                          = 15056,
    Scout_s_MacabreWeb                                = 15060,
    Scout_s_Nutcracker                                = 15061,
    Scout_s_BlueMew                                   = 15100,
    Scout_s_BrainCandy                                = 15101,
    Scout_s_ShottoHell                                = 15102,
    Scout_s_DressedToKill                             = 15126,
    Scout_s_Blitzkrieg                                = 15148,
    Scout_s_TheCAPPER                                 = 30666,
    Scout_t_Bat                                       = 0,
    Scout_t_BatR                                      = 190,
    Scout_t_TheSandman                                = 44,
    Scout_t_TheHolyMackerel                           = 221,
    Scout_t_TheCandyCane                              = 317,
    Scout_t_TheBostonBasher                           = 325,
    Scout_t_SunonaStick                               = 349,
    Scout_t_TheFanOWar                                = 355,
    Scout_t_TheAtomizer                               = 450,
    Scout_t_ThreeRuneBlade                            = 452,
    Scout_t_TheConscientiousObjector                  = 474,
    Scout_t_UnarmedCombat                             = 572,
    Scout_t_TheWrapAssassin                           = 648,
    Scout_t_FestiveBat                                = 660,
    Scout_t_TheFreedomStaff                           = 880,
    Scout_t_TheBatOuttaHell                           = 939,
    Scout_t_TheMemoryMaker                            = 954,
    Scout_t_FestiveHolyMackerel                       = 999,
    Scout_t_TheHamShank                               = 1013,
    Scout_t_TheNecroSmasher                           = 1123,
    Scout_t_TheCrossingGuard                          = 1127,
    Scout_t_Batsaber                                  = 30667,
    Scout_t_PrinnyMachete                             = 30758,
    Soldier_m_RocketLauncher                          = 18,
    Soldier_m_RocketLauncherR                         = 205,
    Soldier_m_TheDirectHit                            = 127,
    Soldier_m_TheBlackBox                             = 228,
    Soldier_m_RocketJumper                            = 237,
    Soldier_m_TheLibertyLauncher                      = 414,
    Soldier_m_TheCowMangler5000                       = 441,
    Soldier_m_TheOriginal                             = 513,
    Soldier_m_FestiveRocketLauncher                   = 658,
    Soldier_m_TheBeggarsBazooka                       = 730,
    Soldier_m_SilverBotkillerRocketLauncherMkI        = 800,
    Soldier_m_GoldBotkillerRocketLauncherMkI          = 809,
    Soldier_m_RustBotkillerRocketLauncherMkI          = 889,
    Soldier_m_BloodBotkillerRocketLauncherMkI         = 898,
    Soldier_m_CarbonadoBotkillerRocketLauncherMkI     = 907,
    Soldier_m_DiamondBotkillerRocketLauncherMkI       = 916,
    Soldier_m_SilverBotkillerRocketLauncherMkII       = 965,
    Soldier_m_GoldBotkillerRocketLauncherMkII         = 974,
    Soldier_m_FestiveBlackBox                         = 1085,
    Soldier_m_TheAirStrike                            = 1104,
    Soldier_m_WoodlandWarrior                         = 15006,
    Soldier_m_SandCannon                              = 15014,
    Soldier_m_AmericanPastoral                        = 15028,
    Soldier_m_SmalltownBringdown                      = 15043,
    Soldier_m_ShellShocker                            = 15052,
    Soldier_m_AquaMarine                              = 15057,
    Soldier_m_Autumn                                  = 15081,
    Soldier_m_BlueMew                                 = 15104,
    Soldier_m_BrainCandy                              = 15105,
    Soldier_m_CoffinNail                              = 15129,
    Soldier_m_HighRollers                             = 15130,
    Soldier_m_Warhawk                                 = 15150,
    Soldier_s_SoldiersShotgun                         = 10,
    Soldier_s_ShotgunR                                = 199,
    Soldier_s_TheBuffBanner                           = 129,
    Soldier_s_Gunboats                                = 133,
    Soldier_s_TheBattalionsBackup                     = 226,
    Soldier_s_TheConcheror                            = 354,
    Soldier_s_TheReserveShooter                       = 415,
    Soldier_s_TheRighteousBison                       = 442,
    Soldier_s_TheMantreads                            = 444,
    Soldier_s_FestiveBuffBanner                       = 1001,
    Soldier_s_TheBASEJumper                           = 1101,
    Soldier_s_FestiveShotgun                          = 1141,
    Soldier_s_PanicAttack                             = 1153,
    Soldier_s_BackwoodsBoomstick                      = 15003,
    Soldier_s_RusticRuiner                            = 15016,
    Soldier_s_CivicDuty                               = 15044,
    Soldier_s_LightningRod                            = 15047,
    Soldier_s_Autumn                                  = 15085,
    Soldier_s_FlowerPower                             = 15109,
    Soldier_s_CoffinNail                              = 15132,
    Soldier_s_DressedtoKill                           = 15133,
    Soldier_s_RedBear                                 = 15152,
    Soldier_t_Shovel                                  = 6,
    Soldier_t_ShovelR                                 = 196,
    Soldier_t_TheEqualizer                            = 128,
    Soldier_t_ThePainTrain                            = 154,
    Soldier_t_TheHalfZatoichi                         = 357,
    Soldier_t_TheMarketGardener                       = 416,
    Soldier_t_TheDisciplinaryAction                   = 447,
    Soldier_t_TheConscientiousObjector                = 474,
    Soldier_t_TheEscapePlan                           = 775,
    Soldier_t_TheFreedomStaff                         = 880,
    Soldier_t_TheBatOuttaHell                         = 939,
    Soldier_t_TheMemoryMaker                          = 954,
    Soldier_t_TheHamShank                             = 1013,
    Soldier_t_TheNecroSmasher                         = 1123,
    Soldier_t_TheCrossingGuard                        = 1127,
    Soldier_t_PrinnyMachete                           = 30758,
    Pyro_m_FlameThrower                               = 21,
    Pyro_m_FlameThrowerR                              = 208,
    Pyro_m_TheBackburner                              = 40,
    Pyro_m_TheDegreaser                               = 215,
    Pyro_m_ThePhlogistinator                          = 594,
    Pyro_m_FestiveFlameThrower                        = 659,
    Pyro_m_TheRainblower                              = 741,
    Pyro_m_SilverBotkillerFlameThrowerMkI             = 798,
    Pyro_m_GoldBotkillerFlameThrowerMkI               = 807,
    Pyro_m_RustBotkillerFlameThrowerMkI               = 887,
    Pyro_m_BloodBotkillerFlameThrowerMkI              = 896,
    Pyro_m_CarbonadoBotkillerFlameThrowerMkI          = 905,
    Pyro_m_DiamondBotkillerFlameThrowerMkI            = 914,
    Pyro_m_SilverBotkillerFlameThrowerMkII            = 963,
    Pyro_m_GoldBotkillerFlameThrowerMkII              = 972,
    Pyro_m_FestiveBackburner                          = 1146,
    Pyro_m_DragonsFury                                = 1178,
    Pyro_m_ForestFire                                 = 15005,
    Pyro_m_BarnBurner                                 = 15017,
    Pyro_m_BovineBlazemaker                           = 15030,
    Pyro_m_EarthSkyandFire                            = 15034,
    Pyro_m_FlashFryer                                 = 15049,
    Pyro_m_TurbineTorcher                             = 15054,
    Pyro_m_Autumn                                     = 15066,
    Pyro_m_PumpkinPatch                               = 15067,
    Pyro_m_Nutcracker                                 = 15068,
    Pyro_m_Balloonicorn                               = 15089,
    Pyro_m_Rainbow                                    = 15090,
    Pyro_m_CoffinNail                                 = 15115,
    Pyro_m_Warhawk                                    = 15141,
    Pyro_m_NostromoNapalmer                           = 30474,
    Pyro_s_PyrosShotgun                               = 12,
    Pyro_s_ShotgunR                                   = 199,
    Pyro_s_TheFlareGun                                = 39,
    Pyro_s_TheDetonator                               = 351,
    Pyro_s_TheReserveShooter                          = 415,
    Pyro_s_TheManmelter                               = 595,
    Pyro_s_TheScorchShot                              = 740,
    Pyro_s_FestiveFlareGun                            = 1081,
    Pyro_s_FestiveShotgun                             = 1141,
    Pyro_s_PanicAttack                                = 1153,
    Pyro_s_ThermalThruster                            = 1179,
    Pyro_s_GasPasser                                  = 1180,
    Pyro_s_BackwoodsBoomstick                         = 15003,
    Pyro_s_RusticRuiner                               = 15016,
    Pyro_s_CivicDuty                                  = 15044,
    Pyro_s_LightningRod                               = 15047,
    Pyro_s_Autumn                                     = 15085,
    Pyro_s_FlowerPower                                = 15109,
    Pyro_s_CoffinNail                                 = 15132,
    Pyro_s_DressedtoKill                              = 15133,
    Pyro_s_RedBear                                    = 15152,
    Pyro_t_FireAxe                                    = 2,
    Pyro_t_FireAxeR                                   = 192,
    Pyro_t_TheAxtinguisher                            = 38,
    Pyro_t_Homewrecker                                = 153,
    Pyro_t_ThePowerjack                               = 214,
    Pyro_t_TheBackScratcher                           = 326,
    Pyro_t_SharpenedVolcanoFragment                   = 348,
    Pyro_t_ThePostalPummeler                          = 457,
    Pyro_t_TheMaul                                    = 466,
    Pyro_t_TheConscientiousObjector                   = 474,
    Pyro_t_TheThirdDegree                             = 593,
    Pyro_t_TheLollichop                               = 739,
    Pyro_t_NeonAnnihilator                            = 813,
    Pyro_t_NeonAnnihilatorG                           = 834,
    Pyro_t_TheFreedomStaff                            = 880,
    Pyro_t_TheBatOuttaHell                            = 939,
    Pyro_t_TheMemoryMaker                             = 954,
    Pyro_t_TheFestiveAxtinguisher                     = 1000,
    Pyro_t_TheHamShank                                = 1013,
    Pyro_t_TheNecroSmasher                            = 1123,
    Pyro_t_TheCrossingGuard                           = 1127,
    Pyro_t_HotHand                                    = 1181,
    Pyro_t_PrinnyMachete                              = 30758,
    Demoman_m_GrenadeLauncher                         = 19,
    Demoman_m_GrenadeLauncherR                        = 206,
    Demoman_m_TheLochnLoad                            = 308,
    Demoman_m_AliBabasWeeBooties                      = 405,
    Demoman_m_TheBootlegger                           = 608,
    Demoman_m_TheLooseCannon                          = 996,
    Demoman_m_FestiveGrenadeLauncher                  = 1007,
    Demoman_m_TheBASEJumper                           = 1101,
    Demoman_m_TheIronBomber                           = 1151,
    Demoman_m_Autumn                                  = 15077,
    Demoman_m_MacabreWeb                              = 15079,
    Demoman_m_Rainbow                                 = 15091,
    Demoman_m_SweetDreams                             = 15092,
    Demoman_m_CoffinNail                              = 15116,
    Demoman_m_TopShelf                                = 15117,
    Demoman_m_Warhawk                                 = 15142,
    Demoman_m_ButcherBird                             = 15158,
    Demoman_s_StickybombLauncher                      = 20,
    Demoman_s_StickybombLauncherR                     = 207,
    Demoman_s_TheScottishResistance                   = 130,
    Demoman_s_TheCharginTarge                         = 131,
    Demoman_s_StickyJumper                            = 265,
    Demoman_s_TheSplendidScreen                       = 406,
    Demoman_s_FestiveStickybombLauncher               = 661,
    Demoman_s_SilverBotkillerStickybombLauncherMkI    = 797,
    Demoman_s_GoldBotkillerStickybombLauncherMkI      = 806,
    Demoman_s_RustBotkillerStickybombLauncherMkI      = 886,
    Demoman_s_BloodBotkillerStickybombLauncherMkI     = 895,
    Demoman_s_CarbonadoBotkillerStickybombLauncherMkI = 904,
    Demoman_s_DiamondBotkillerStickybombLauncherMkI   = 913,
    Demoman_s_SilverBotkillerStickybombLauncherMkII   = 962,
    Demoman_s_GoldBotkillerStickybombLauncherMkII     = 971,
    Demoman_s_TheTideTurner                           = 1099,
    Demoman_s_FestiveTarge                            = 1144,
    Demoman_s_TheQuickiebombLauncher                  = 1150,
    Demoman_s_SuddenFlurry                            = 15009,
    Demoman_s_CarpetBomber                            = 15012,
    Demoman_s_BlastedBombardier                       = 15024,
    Demoman_s_RooftopWrangler                         = 15038,
    Demoman_s_LiquidAsset                             = 15045,
    Demoman_s_PinkElephant                            = 15048,
    Demoman_s_Autumn                                  = 15082,
    Demoman_s_PumpkinPatch                            = 15083,
    Demoman_s_MacabreWeb                              = 15084,
    Demoman_s_SweetDreams                             = 15113,
    Demoman_s_CoffinNail                              = 15137,
    Demoman_s_DressedtoKill                           = 15138,
    Demoman_s_Blitzkrieg                              = 15155,
    Demoman_t_Bottle                                  = 1,
    Demoman_t_BottleR                                 = 191,
    Demoman_t_TheEyelander                            = 132,
    Demoman_t_ThePainTrain                            = 154,
    Demoman_t_TheScotsmansSkullcutter                 = 172,
    Demoman_t_HorselessHeadlessHorsemannsHeadtaker    = 266,
    Demoman_t_UllapoolCaber                           = 307,
    Demoman_t_TheClaidheamhMor                        = 327,
    Demoman_t_TheHalfZatoichi                         = 357,
    Demoman_t_ThePersianPersuader                     = 404,
    Demoman_t_TheConscientiousObjector                = 474,
    Demoman_t_NessiesNineIron                         = 482,
    Demoman_t_TheScottishHandshake                    = 609,
    Demoman_t_TheFreedomStaff                         = 880,
    Demoman_t_TheBatOuttaHell                         = 939,
    Demoman_t_TheMemoryMaker                          = 954,
    Demoman_t_TheHamShank                             = 1013,
    Demoman_t_FestiveEyelander                        = 1082,
    Demoman_t_TheNecroSmasher                         = 1123,
    Demoman_t_TheCrossingGuard                        = 1127,
    Demoman_t_PrinnyMachete                           = 30758,
    Heavy_m_Minigun                                   = 15,
    Heavy_m_MinigunR                                  = 202,
    Heavy_m_Natascha                                  = 41,
    Heavy_m_IronCurtain                               = 298,
    Heavy_m_TheBrassBeast                             = 312,
    Heavy_m_Tomislav                                  = 424,
    Heavy_m_FestiveMinigun                            = 654,
    Heavy_m_SilverBotkillerMinigunMkI                 = 793,
    Heavy_m_GoldBotkillerMinigunMkI                   = 802,
    Heavy_m_TheHuoLongHeater                          = 811,
    Heavy_m_TheHuoLongHeaterG                         = 832,
    Heavy_m_Deflector_mvm                             = 850,
    Heavy_m_RustBotkillerMinigunMkI                   = 882,
    Heavy_m_BloodBotkillerMinigunMkI                  = 891,
    Heavy_m_CarbonadoBotkillerMinigunMkI              = 900,
    Heavy_m_DiamondBotkillerMinigunMkI                = 909,
    Heavy_m_SilverBotkillerMinigunMkII                = 958,
    Heavy_m_GoldBotkillerMinigunMkII                  = 967,
    Heavy_m_KingoftheJungle                           = 15004,
    Heavy_m_IronWood                                  = 15020,
    Heavy_m_AntiqueAnnihilator                        = 15026,
    Heavy_m_WarRoom                                   = 15031,
    Heavy_m_CitizenPain                               = 15040,
    Heavy_m_BrickHouse                                = 15055,
    Heavy_m_MacabreWeb                                = 15086,
    Heavy_m_PumpkinPatch                              = 15087,
    Heavy_m_Nutcracker                                = 15088,
    Heavy_m_BrainCandy                                = 15098,
    Heavy_m_MisterCuddles                             = 15099,
    Heavy_m_CoffinNail                                = 15123,
    Heavy_m_DressedtoKill                             = 15124,
    Heavy_m_TopShelf                                  = 15125,
    Heavy_m_ButcherBird                               = 15147,
    Heavy_s_HeavysShotgun                             = 11,
    Heavy_s_ShotgunR                                  = 199,
    Heavy_s_Sandvich                                  = 42,
    Heavy_s_TheDalokohsBar                            = 159,
    Heavy_s_TheBuffaloSteakSandvich                   = 311,
    Heavy_s_TheFamilyBusiness                         = 425,
    Heavy_s_Fishcake                                  = 433,
    Heavy_s_RoboSandvich                              = 863,
    Heavy_s_FestiveSandvich                           = 1002,
    Heavy_s_FestiveShotgun                            = 1141,
    Heavy_s_PanicAttack                               = 1153,
    Heavy_s_SecondBanana                              = 1190,
    Heavy_s_BackwoodsBoomstick                        = 15003,
    Heavy_s_RusticRuiner                              = 15016,
    Heavy_s_CivicDuty                                 = 15044,
    Heavy_s_LightningRod                              = 15047,
    Heavy_s_Autumn                                    = 15085,
    Heavy_s_FlowerPower                               = 15109,
    Heavy_s_CoffinNail                                = 15132,
    Heavy_s_DressedtoKill                             = 15133,
    Heavy_s_RedBear                                   = 15152,
    Heavy_t_Fists                                     = 5,
    Heavy_t_FistsR                                    = 195,
    Heavy_t_TheKillingGlovesofBoxing                  = 43,
    Heavy_t_GlovesofRunningUrgently                   = 239,
    Heavy_t_WarriorsSpirit                            = 310,
    Heavy_t_FistsofSteel                              = 331,
    Heavy_t_TheEvictionNotice                         = 426,
    Heavy_t_TheConscientiousObjector                  = 474,
    Heavy_t_ApocoFists                                = 587,
    Heavy_t_TheHolidayPunch                           = 656,
    Heavy_t_TheFreedomStaff                           = 880,
    Heavy_t_TheBatOuttaHell                           = 939,
    Heavy_t_TheMemoryMaker                            = 954,
    Heavy_t_TheHamShank                               = 1013,
    Heavy_t_FestiveGlovesofRunningUrgently            = 1084,
    Heavy_t_TheBreadBite                              = 1100,
    Heavy_t_TheNecroSmasher                           = 1123,
    Heavy_t_TheCrossingGuard                          = 1127,
    Heavy_t_GlovesofRunningUrgentlyMvM                = 1184,
    Heavy_t_PrinnyMachete                             = 30758,
    Engi_m_EngineersShotgun                           = 9,
    Engi_m_ShotgunR                                   = 199,
    Engi_m_TheFrontierJustice                         = 141,
    Engi_m_TheWidowmaker                              = 527,
    Engi_m_ThePomson6000                              = 588,
    Engi_m_TheRescueRanger                            = 997,
    Engi_m_FestiveFrontierJustice                     = 1004,
    Engi_m_FestiveShotgun                             = 1141,
    Engi_m_PanicAttack                                = 1153,
    Engi_m_BackwoodsBoomstick                         = 15003,
    Engi_m_RusticRuiner                               = 15016,
    Engi_m_CivicDuty                                  = 15044,
    Engi_m_LightningRod                               = 15047,
    Engi_m_Autumn                                     = 15085,
    Engi_m_FlowerPower                                = 15109,
    Engi_m_CoffinNail                                 = 15132,
    Engi_m_DressedtoKill                              = 15133,
    Engi_m_RedBear                                    = 15152,
    Engi_s_EngineersPistol                            = 22,
    Engi_s_PistolR                                    = 209,
    Engi_s_TheWrangler                                = 140,
    Engi_s_VintageLugermorph                          = 160,
    Engi_s_Lugermorph                                 = 294,
    Engi_s_TheShortCircuit                            = 528,
    Engi_s_FestiveWrangler                            = 1086,
    Engi_s_RedRockRoscoe                              = 15013,
    Engi_s_HomemadeHeater                             = 15018,
    Engi_s_HickoryHolepuncher                         = 15035,
    Engi_s_LocalHero                                  = 15041,
    Engi_s_BlackDahlia                                = 15046,
    Engi_s_SandstoneSpecial                           = 15056,
    Engi_s_MacabreWeb                                 = 15060,
    Engi_s_Nutcracker                                 = 15061,
    Engi_s_BlueMew                                    = 15100,
    Engi_s_BrainCandy                                 = 15101,
    Engi_s_ShottoHell                                 = 15102,
    Engi_s_DressedToKill                              = 15126,
    Engi_s_Blitzkrieg                                 = 15148,
    Engi_s_TheCAPPER                                  = 30666,
    Engi_s_TheGigarCounter                            = 30668,
    Engi_t_Wrench                                     = 7,
    Engi_t_WrenchR                                    = 197,
    Engi_t_TheGunslinger                              = 142,
    Engi_t_TheSouthernHospitality                     = 155,
    Engi_t_GoldenWrench                               = 169,
    Engi_t_TheJag                                     = 329,
    Engi_t_TheEurekaEffect                            = 589,
    Engi_t_FestiveWrench                              = 662,
    Engi_t_SilverBotkillerWrenchMkI                   = 795,
    Engi_t_GoldBotkillerWrenchMkI                     = 804,
    Engi_t_RustBotkillerWrenchMkI                     = 884,
    Engi_t_BloodBotkillerWrenchMkI                    = 893,
    Engi_t_CarbonadoBotkillerWrenchMkI                = 902,
    Engi_t_DiamondBotkillerWrenchMkI                  = 911,
    Engi_t_SilverBotkillerWrenchMkII                  = 960,
    Engi_t_GoldBotkillerWrenchMkII                    = 969,
    Engi_t_TheNecroSmasher                            = 1123,
    Engi_t_Nutcracker                                 = 15073,
    Engi_t_Autumn                                     = 15074,
    Engi_t_Boneyard                                   = 15075,
    Engi_t_DressedtoKill                              = 15139,
    Engi_t_TopShelf                                   = 15140,
    Engi_t_TorquedtoHell                              = 15114,
    Engi_t_Airwolf                                    = 15156,
    Engi_t_PrinnyMachete                              = 30758,
    Engi_p_ConstructionPDA                            = 25,
    Engi_p_ConstructionPDAR                           = 737,
    Engi_p_DestructionPDA                             = 26,
    Engi_p_PDA                                        = 28,
    Medic_m_SyringeGun                                = 17,
    Medic_m_SyringeGunR                               = 204,
    Medic_m_TheBlutsauger                             = 36,
    Medic_m_CrusadersCrossbow                         = 305,
    Medic_m_TheOverdose                               = 412,
    Medic_m_FestiveCrusadersCrossbow                  = 1079,
    Medic_s_MediGun                                   = 29,
    Medic_s_MediGunR                                  = 211,
    Medic_s_TheKritzkrieg                             = 35,
    Medic_s_TheQuickFix                               = 411,
    Medic_s_FestiveMediGun                            = 663,
    Medic_s_SilverBotkillerMediGunMkI                 = 796,
    Medic_s_GoldBotkillerMediGunMkI                   = 805,
    Medic_s_RustBotkillerMediGunMkI                   = 885,
    Medic_s_BloodBotkillerMediGunMkI                  = 894,
    Medic_s_CarbonadoBotkillerMediGunMkI              = 903,
    Medic_s_DiamondBotkillerMediGunMkI                = 912,
    Medic_s_SilverBotkillerMediGunMkII                = 961,
    Medic_s_GoldBotkillerMediGunMkII                  = 970,
    Medic_s_TheVaccinator                             = 998,
    Medic_s_MaskedMender                              = 15008,
    Medic_s_WrappedReviver                            = 15010,
    Medic_s_ReclaimedReanimator                       = 15025,
    Medic_s_CivilServant                              = 15039,
    Medic_s_SparkofLife                               = 15050,
    Medic_s_Wildwood                                  = 15078,
    Medic_s_FlowerPower                               = 15097,
    Medic_s_DressedToKill                             = 15121,
    Medic_s_HighRollers                               = 15122,
    Medic_s_CoffinNail                                = 15123,
    Medic_s_Blitzkrieg                                = 15145,
    Medic_s_Corsair                                   = 15146,
    Medic_t_Bonesaw                                   = 8,
    Medic_t_BonesawR                                  = 198,
    Medic_t_TheUbersaw                                = 37,
    Medic_t_TheVitaSaw                                = 173,
    Medic_t_Amputator                                 = 304,
    Medic_t_TheSolemnVow                              = 413,
    Medic_t_TheConscientiousObjector                  = 474,
    Medic_t_TheFreedomStaff                           = 880,
    Medic_t_TheBatOuttaHell                           = 939,
    Medic_t_TheMemoryMaker                            = 954,
    Medic_t_FestiveUbersaw                            = 1003,
    Medic_t_TheHamShank                               = 1013,
    Medic_t_TheNecroSmasher                           = 1123,
    Medic_t_TheCrossingGuard                          = 1127,
    Medic_t_FestiveBonesaw                            = 1143,
    Medic_t_PrinnyMachete                             = 30758,
    Sniper_m_SniperRifle                              = 14,
    Sniper_m_SniperRifleR                             = 201,
    Sniper_m_TheHuntsman                              = 56,
    Sniper_m_TheSydneySleeper                         = 230,
    Sniper_m_TheBazaarBargain                         = 402,
    Sniper_m_TheMachina                               = 526,
    Sniper_m_FestiveSniperRifle                       = 664,
    Sniper_m_TheHitmansHeatmaker                      = 752,
    Sniper_m_SilverBotkillerSniperRifleMkI            = 792,
    Sniper_m_GoldBotkillerSniperRifleMkI              = 801,
    Sniper_m_TheAWPerHand                             = 851,
    Sniper_m_RustBotkillerSniperRifleMkI              = 881,
    Sniper_m_BloodBotkillerSniperRifleMkI             = 890,
    Sniper_m_CarbonadoBotkillerSniperRifleMkI         = 899,
    Sniper_m_DiamondBotkillerSniperRifleMkI           = 908,
    Sniper_m_SilverBotkillerSniperRifleMkII           = 957,
    Sniper_m_GoldBotkillerSniperRifleMkII             = 966,
    Sniper_m_FestiveHuntsman                          = 1005,
    Sniper_m_TheFortifiedCompound                     = 1092,
    Sniper_m_TheClassic                               = 1098,
    Sniper_m_NightOwl                                 = 15000,
    Sniper_m_PurpleRange                              = 15007,
    Sniper_m_LumberFromDownUnder                      = 15019,
    Sniper_m_ShotintheDark                            = 15023,
    Sniper_m_Bogtrotter                               = 15033,
    Sniper_m_Thunderbolt                              = 15059,
    Sniper_m_PumpkinPatch                             = 15070,
    Sniper_m_Boneyard                                 = 15071,
    Sniper_m_Wildwood                                 = 15072,
    Sniper_m_Balloonicorn                             = 15111,
    Sniper_m_Rainbow                                  = 15112,
    Sniper_m_CoffinNail                               = 15135,
    Sniper_m_DressedtoKill                            = 15136,
    Sniper_m_Airwolf                                  = 15154,
    Sniper_m_ShootingStar                             = 30665,
    Sniper_s_SMG                                      = 16,
    Sniper_s_SMGR                                     = 203,
    Sniper_s_TheRazorback                             = 57,
    Sniper_s_Jarate                                   = 58,
    Sniper_s_DarwinsDangerShield                      = 231,
    Sniper_s_CozyCamper                               = 642,
    Sniper_s_TheCleanersCarbine                       = 751,
    Sniper_s_FestiveJarate                            = 1083,
    Sniper_s_TheSelfAwareBeautyMark                   = 1105,
    Sniper_s_FestiveSMG                               = 1149,
    Sniper_s_WoodsyWidowmaker                         = 15001,
    Sniper_s_PlaidPotshotter                          = 15022,
    Sniper_s_TreadplateTormenter                      = 15032,
    Sniper_s_TeamSprayer                              = 15037,
    Sniper_s_LowProfile                               = 15058,
    Sniper_s_Wildwood                                 = 15076,
    Sniper_s_BlueMew                                  = 15110,
    Sniper_s_HighRollers                              = 15134,
    Sniper_s_Blitzkrieg                               = 15153,
    Sniper_t_Kukri                                    = 3,
    Sniper_t_KukriR                                   = 193,
    Sniper_t_TheTribalmansShiv                        = 171,
    Sniper_t_TheBushwacka                             = 232,
    Sniper_t_TheShahanshah                            = 401,
    Sniper_t_TheConscientiousObjector                 = 474,
    Sniper_t_TheFreedomStaff                          = 880,
    Sniper_t_TheBatOuttaHell                          = 939,
    Sniper_t_TheMemoryMaker                           = 954,
    Sniper_t_TheHamShank                              = 1013,
    Sniper_t_TheNecroSmasher                          = 1123,
    Sniper_t_TheCrossingGuard                         = 1127,
    Sniper_t_PrinnyMachete                            = 30758,
    Spy_m_Revolver                                    = 24,
    Spy_m_RevolverR                                   = 210,
    Spy_m_TheAmbassador                               = 61,
    Spy_m_BigKill                                     = 161,
    Spy_m_LEtranger                                   = 224,
    Spy_m_TheEnforcer                                 = 460,
    Spy_m_TheDiamondback                              = 525,
    Spy_m_FestiveAmbassador                           = 1006,
    Spy_m_FestiveRevolver                             = 1142,
    Spy_m_PsychedelicSlugger                          = 15011,
    Spy_m_OldCountry                                  = 15027,
    Spy_m_Mayor                                       = 15042,
    Spy_m_DeadReckoner                                = 15051,
    Spy_m_Boneyard                                    = 15062,
    Spy_m_Wildwood                                    = 15063,
    Spy_m_MacabreWeb                                  = 15064,
    Spy_m_FlowerPower                                 = 15103,
    Spy_m_TopShelf                                    = 15128,
    Spy_m_CoffinNail                                  = 15129,
    Spy_m_Blitzkrieg                                  = 15149,
    Spy_s_Sapper                                      = 735,
    Spy_s_SapperR                                     = 736,
    Spy_s_TheRedTapeRecorder                          = 810,
    Spy_s_TheRedTapeRecorderG                         = 831,
    Spy_s_TheApSapG                                   = 933,
    Spy_s_FestiveSapper                               = 1080,
    Spy_s_TheSnackAttack                              = 1102,
    Spy_t_Knife                                       = 4,
    Spy_t_KnifeR                                      = 194,
    Spy_t_YourEternalReward                           = 225,
    Spy_t_ConniversKunai                              = 356,
    Spy_t_TheBigEarner                                = 461,
    Spy_t_TheWangaPrick                               = 574,
    Spy_t_TheSharpDresser                             = 638,
    Spy_t_TheSpycicle                                 = 649,
    Spy_t_FestiveKnife                                = 665,
    Spy_t_TheBlackRose                                = 727,
    Spy_t_SilverBotkillerKnifeMkI                     = 794,
    Spy_t_GoldBotkillerKnifeMkI                       = 803,
    Spy_t_RustBotkillerKnifeMkI                       = 883,
    Spy_t_BloodBotkillerKnifeMkI                      = 892,
    Spy_t_CarbonadoBotkillerKnifeMkI                  = 901,
    Spy_t_DiamondBotkillerKnifeMkI                    = 910,
    Spy_t_SilverBotkillerKnifeMkII                    = 959,
    Spy_t_GoldBotkillerKnifeMkII                      = 968,
    Spy_t_Boneyard                                    = 15062,
    Spy_t_BlueMew                                     = 15094,
    Spy_t_BrainCandy                                  = 15095,
    Spy_t_StabbedtoHell                               = 15096,
    Spy_t_DressedtoKill                               = 15118,
    Spy_t_TopShelf                                    = 15119,
    Spy_t_Blitzkrieg                                  = 15143,
    Spy_t_Airwolf                                     = 15144,
    Spy_t_PrinnyMachete                               = 30758,
    Spy_d_DisguiseKitPDA                              = 27,
    Spy_w_InvisWatch                                  = 30,
    Spy_w_InvisWatchR                                 = 212,
    Spy_w_TheDeadRinger                               = 59,
    Spy_w_TheCloakandDagger                           = 60,
    Spy_w_EnthusiastsTimepiece                        = 297,
    Spy_w_TheQuackenbirdt                             = 947,
    Misc_t_FryingPan                                  = 264,
    Misc_t_GoldFryingPan                              = 1071,
    Misc_t_Saxxy                                      = 423,
};

/* Grenade Launcher modes (for pipebombs) */
enum {
    TF_GL_MODE_REGULAR = 0,
    TF_GL_MODE_REMOTE_DETONATE,
    TF_GL_MODE_REMOTE_DETONATE_PRACTICE,
    TF_GL_MODE_CANNONBALL,
};

/* CBaseHandle */
#define MAX_EDICT_BITS        11
#define MAX_EDICTS            (1 << MAX_EDICT_BITS)
#define NUM_ENT_ENTRY_BITS    (MAX_EDICT_BITS + 1)
#define NUM_ENT_ENTRIES       (1 << NUM_ENT_ENTRY_BITS)
#define ENT_ENTRY_MASK        (NUM_ENT_ENTRIES - 1)
#define INVALID_EHANDLE_INDEX 0xFFFFFFFF

#define MAX_WEAPON_SLOTS     6  /* hud item selection slots */
#define MAX_WEAPON_POSITIONS 20 /* max number of items within a slot */
#define MAX_ITEM_TYPES       6  /* hud item selection slots */
#define MAX_WEAPONS          48 /* Max number of weapons available */

enum ETFClass {
    CLASS_NONE = 0,
    CLASS_SCOUT,
    CLASS_SNIPER,
    CLASS_SOLDIER,
    CLASS_DEMOMAN,
    CLASS_MEDIC,
    CLASS_HEAVY,
    CLASS_PYRO,
    CLASS_SPY,
    CLASS_ENGINEER
};

enum BoneMasks {
    BONE_USED_MASK           = 0x0007FF00,
    BONE_USED_BY_ANYTHING    = 0x0007FF00,
    BONE_USED_BY_HITBOX      = 0x00000100,
    BONE_USED_BY_ATTACHMENT  = 0x00000200,
    BONE_USED_BY_VERTEX_MASK = 0x0003FC00,
    BONE_USED_BY_VERTEX_LOD0 = 0x00000400,
    BONE_USED_BY_VERTEX_LOD1 = 0x00000800,
    BONE_USED_BY_VERTEX_LOD2 = 0x00001000,
    BONE_USED_BY_VERTEX_LOD3 = 0x00002000,
    BONE_USED_BY_VERTEX_LOD4 = 0x00004000,
    BONE_USED_BY_VERTEX_LOD5 = 0x00008000,
    BONE_USED_BY_VERTEX_LOD6 = 0x00010000,
    BONE_USED_BY_VERTEX_LOD7 = 0x00020000,
    BONE_USED_BY_BONE_MERGE  = 0x00040000,
};

enum ObsModes {
    OBS_MODE_NONE = 0,
    OBS_MODE_DEATHCAM,
    OBS_MODE_FREEZECAM,
    OBS_MODE_FIXED,
    OBS_MODE_IN_EYE,
    OBS_MODE_CHASE,
    OBS_MODE_POI,
    OBS_MODE_ROAMING,
    NUM_OBSERVER_MODES,
};

/*----------------------------------------------------------------------------*/

/* "flag" argument of IMaterial::SetMaterialVarFlag() */
enum MaterialVarFlags_t {
    MATERIAL_VAR_DEBUG                    = (1 << 0),
    MATERIAL_VAR_NO_DEBUG_OVERRIDE        = (1 << 1),
    MATERIAL_VAR_NO_DRAW                  = (1 << 2),
    MATERIAL_VAR_USE_IN_FILLRATE_MODE     = (1 << 3),
    MATERIAL_VAR_VERTEXCOLOR              = (1 << 4),
    MATERIAL_VAR_VERTEXALPHA              = (1 << 5),
    MATERIAL_VAR_SELFILLUM                = (1 << 6),
    MATERIAL_VAR_ADDITIVE                 = (1 << 7),
    MATERIAL_VAR_ALPHATEST                = (1 << 8),
    MATERIAL_VAR_MULTIPASS                = (1 << 9),
    MATERIAL_VAR_ZNEARER                  = (1 << 10),
    MATERIAL_VAR_MODEL                    = (1 << 11),
    MATERIAL_VAR_FLAT                     = (1 << 12),
    MATERIAL_VAR_NOCULL                   = (1 << 13),
    MATERIAL_VAR_NOFOG                    = (1 << 14),
    MATERIAL_VAR_IGNOREZ                  = (1 << 15),
    MATERIAL_VAR_DECAL                    = (1 << 16),
    MATERIAL_VAR_ENVMAPSPHERE             = (1 << 17),
    MATERIAL_VAR_NOALPHAMOD               = (1 << 18),
    MATERIAL_VAR_ENVMAPCAMERASPACE        = (1 << 19),
    MATERIAL_VAR_BASEALPHAENVMAPMASK      = (1 << 20),
    MATERIAL_VAR_TRANSLUCENT              = (1 << 21),
    MATERIAL_VAR_NORMALMAPALPHAENVMAPMASK = (1 << 22),
    MATERIAL_VAR_NEEDS_SOFTWARE_SKINNING  = (1 << 23),
    MATERIAL_VAR_OPAQUETEXTURE            = (1 << 24),
    MATERIAL_VAR_ENVMAPMODE               = (1 << 25),
    MATERIAL_VAR_SUPPRESS_DECALS          = (1 << 26),
    MATERIAL_VAR_HALFLAMBERT              = (1 << 27),
    MATERIAL_VAR_WIREFRAME                = (1 << 28),
    MATERIAL_VAR_ALLOWALPHATOCOVERAGE     = (1 << 29),
    MATERIAL_VAR_IGNORE_ALPHA_MODULATION  = (1 << 30),
};

/* "nOverrideType" argument of ModelRender::ForcedMaterialOverride() */
enum OverrideType_t {
    OVERRIDE_NORMAL = 0,
    OVERRIDE_BUILD_SHADOWS,
    OVERRIDE_DEPTH_WRITE,
    OVERRIDE_SSAO_DEPTH_WRITE,
};

/* From csgo, might be wrong/outdated. Currently using GROUP_MODEL */
#define TEXTURE_GROUP_LIGHTMAP                    "Lightmaps"
#define TEXTURE_GROUP_WORLD                       "World textures"
#define TEXTURE_GROUP_MODEL                       "Model textures"
#define TEXTURE_GROUP_VGUI                        "VGUI textures"
#define TEXTURE_GROUP_PARTICLE                    "Particle textures"
#define TEXTURE_GROUP_DECAL                       "Decal textures"
#define TEXTURE_GROUP_SKYBOX                      "SkyBox textures"
#define TEXTURE_GROUP_CLIENT_EFFECTS              "ClientEffect textures"
#define TEXTURE_GROUP_OTHER                       "Other textures"
#define TEXTURE_GROUP_PRECACHED                   "Precached"
#define TEXTURE_GROUP_CUBE_MAP                    "CubeMap textures"
#define TEXTURE_GROUP_RENDER_TARGET               "RenderTargets"
#define TEXTURE_GROUP_UNACCOUNTED                 "Unaccounted textures"
#define TEXTURE_GROUP_STATIC_INDEX_BUFFER         "Static Indices"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_DISP   "Displacement Verts"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_COLOR  "Lighting Verts"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_WORLD  "World Verts"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_MODELS "Model Verts"
#define TEXTURE_GROUP_STATIC_VERTEX_BUFFER_OTHER  "Other Verts"
#define TEXTURE_GROUP_DYNAMIC_INDEX_BUFFER        "Dynamic Indices"
#define TEXTURE_GROUP_DYNAMIC_VERTEX_BUFFER       "Dynamic Verts"
#define TEXTURE_GROUP_DEPTH_BUFFER                "DepthBuffer"
#define TEXTURE_GROUP_VIEW_MODEL                  "ViewModel"
#define TEXTURE_GROUP_PIXEL_SHADERS               "Pixel Shaders"
#define TEXTURE_GROUP_VERTEX_SHADERS              "Vertex Shaders"
#define TEXTURE_GROUP_RENDER_TARGET_SURFACE       "RenderTarget Surfaces"
#define TEXTURE_GROUP_MORPH_TARGETS               "Morph Targets"

/*----------------------------------------------------------------------------*/

#define DMG_GENERIC               0
#define DMG_CRUSH                 (1 << 0)
#define DMG_BULLET                (1 << 1)
#define DMG_SLASH                 (1 << 2)
#define DMG_BURN                  (1 << 3)
#define DMG_VEHICLE               (1 << 4)
#define DMG_FALL                  (1 << 5)
#define DMG_BLAST                 (1 << 6)
#define DMG_CLUB                  (1 << 7)
#define DMG_SHOCK                 (1 << 8)
#define DMG_SONIC                 (1 << 9)
#define DMG_ENERGYBEAM            (1 << 10)
#define DMG_PREVENT_PHYSICS_FORCE (1 << 11)
#define DMG_NEVERGIB              (1 << 12)
#define DMG_ALWAYSGIB             (1 << 13)
#define DMG_DROWN                 (1 << 14)
#define DMG_PARALYZE              (1 << 15)
#define DMG_NERVEGAS              (1 << 16)
#define DMG_POISON                (1 << 17)
#define DMG_RADIATION             (1 << 18)
#define DMG_DROWNRECOVER          (1 << 19)
#define DMG_ACID                  (1 << 20)
#define DMG_SLOWBURN              (1 << 21)
#define DMG_REMOVENORAGDOLL       (1 << 22)
#define DMG_PHYSGUN               (1 << 23)
#define DMG_PLASMA                (1 << 24)
#define DMG_AIRBOAT               (1 << 25)
#define DMG_DISSOLVE              (1 << 26)
#define DMG_BLAST_SURFACE         (1 << 27)
#define DMG_DIRECT                (1 << 28)
#define DMG_BUCKSHOT              (1 << 29)

enum {
    WPN_SLOT_PRIMARY   = 0,
    WPN_SLOT_SECONDARY = 1,
    WPN_SLOT_MELEE     = 2,
    WPN_SLOT_GRENADES  = 3,
    WPN_SLOT_BOMB      = 4,
};

/*----------------------------------------------------------------------------*/

enum ETFCond {
    TF_COND_INVALID = -1,
    TF_COND_AIMING,
    TF_COND_ZOOMED,
    TF_COND_DISGUISING,
    TF_COND_DISGUISED,
    TF_COND_STEALTHED,
    TF_COND_INVULNERABLE,
    TF_COND_TELEPORTED,
    TF_COND_TAUNTING,
    TF_COND_INVULNERABLE_WEARINGOFF,
    TF_COND_STEALTHED_BLINK,
    TF_COND_SELECTED_TO_TELEPORT,
    TF_COND_CRITBOOSTED,
    TF_COND_TMPDAMAGEBONUS,
    TF_COND_FEIGN_DEATH,
    TF_COND_PHASE,
    TF_COND_STUNNED,
    TF_COND_OFFENSEBUFF,
    TF_COND_SHIELD_CHARGE,
    TF_COND_DEMO_BUFF,
    TF_COND_ENERGY_BUFF,
    TF_COND_RADIUSHEAL,
    TF_COND_HEALTH_BUFF,
    TF_COND_BURNING,
    TF_COND_HEALTH_OVERHEALED,
    TF_COND_URINE,
    TF_COND_BLEEDING,
    TF_COND_DEFENSEBUFF,
    TF_COND_MAD_MILK,
    TF_COND_MEGAHEAL,
    TF_COND_REGENONDAMAGEBUFF,
    TF_COND_MARKEDFORDEATH,
    TF_COND_NOHEALINGDAMAGEBUFF,
    TF_COND_SPEED_BOOST,
    TF_COND_CRITBOOSTED_PUMPKIN,
    TF_COND_CRITBOOSTED_USER_BUFF,
    TF_COND_CRITBOOSTED_DEMO_CHARGE,
    TF_COND_SODAPOPPER_HYPE,
    TF_COND_CRITBOOSTED_FIRST_BLOOD,
    TF_COND_CRITBOOSTED_BONUS_TIME,
    TF_COND_CRITBOOSTED_CTF_CAPTURE,
    TF_COND_CRITBOOSTED_ON_KILL,
    TF_COND_CANNOT_SWITCH_FROM_MELEE,
    TF_COND_DEFENSEBUFF_NO_CRIT_BLOCK,
    TF_COND_REPROGRAMMED,
    TF_COND_CRITBOOSTED_RAGE_BUFF,
    TF_COND_DEFENSEBUFF_HIGH,
    TF_COND_SNIPERCHARGE_RAGE_BUFF,
    TF_COND_DISGUISE_WEARINGOFF,
    TF_COND_MARKEDFORDEATH_SILENT,
    TF_COND_DISGUISED_AS_DISPENSER,
    TF_COND_SAPPED,
    TF_COND_INVULNERABLE_HIDE_UNLESS_DAMAGE,
    TF_COND_INVULNERABLE_USER_BUFF,
    TF_COND_HALLOWEEN_BOMB_HEAD,
    TF_COND_HALLOWEEN_THRILLER,
    TF_COND_RADIUSHEAL_ON_DAMAGE,
    TF_COND_CRITBOOSTED_CARD_EFFECT,
    TF_COND_INVULNERABLE_CARD_EFFECT,
    TF_COND_MEDIGUN_UBER_BULLET_RESIST,
    TF_COND_MEDIGUN_UBER_BLAST_RESIST,
    TF_COND_MEDIGUN_UBER_FIRE_RESIST,
    TF_COND_MEDIGUN_SMALL_BULLET_RESIST,
    TF_COND_MEDIGUN_SMALL_BLAST_RESIST,
    TF_COND_MEDIGUN_SMALL_FIRE_RESIST,
    TF_COND_STEALTHED_USER_BUFF,
    TF_COND_MEDIGUN_DEBUFF,
    TF_COND_STEALTHED_USER_BUFF_FADING,
    TF_COND_BULLET_IMMUNE,
    TF_COND_BLAST_IMMUNE,
    TF_COND_FIRE_IMMUNE,
    TF_COND_PREVENT_DEATH,
    TF_COND_MVM_BOT_STUN_RADIOWAVE,
    TF_COND_HALLOWEEN_SPEED_BOOST,
    TF_COND_HALLOWEEN_QUICK_HEAL,
    TF_COND_HALLOWEEN_GIANT,
    TF_COND_HALLOWEEN_TINY,
    TF_COND_HALLOWEEN_IN_HELL,
    TF_COND_HALLOWEEN_GHOST_MODE,
    TF_COND_MINICRITBOOSTED_ON_KILL,
    TF_COND_OBSCURED_SMOKE,
    TF_COND_PARACHUTE_ACTIVE,
    TF_COND_BLASTJUMPING,
    TF_COND_HALLOWEEN_KART,
    TF_COND_HALLOWEEN_KART_DASH,
    TF_COND_BALLOON_HEAD,
    TF_COND_MELEE_ONLY,
    TF_COND_SWIMMING_CURSE,
    TF_COND_FREEZE_INPUT,
    TF_COND_HALLOWEEN_KART_CAGE,
    TF_COND_DONOTUSE_0,
    TF_COND_RUNE_STRENGTH,
    TF_COND_RUNE_HASTE,
    TF_COND_RUNE_REGEN,
    TF_COND_RUNE_RESIST,
    TF_COND_RUNE_VAMPIRE,
    TF_COND_RUNE_REFLECT,
    TF_COND_RUNE_PRECISION,
    TF_COND_RUNE_AGILITY,
    TF_COND_GRAPPLINGHOOK,
    TF_COND_GRAPPLINGHOOK_SAFEFALL,
    TF_COND_GRAPPLINGHOOK_LATCHED,
    TF_COND_GRAPPLINGHOOK_BLEEDING,
    TF_COND_AFTERBURN_IMMUNE,
    TF_COND_RUNE_KNOCKOUT,
    TF_COND_RUNE_IMBALANCE,
    TF_COND_CRITBOOSTED_RUNE_TEMP,
    TF_COND_PASSTIME_INTERCEPTION,
    TF_COND_SWIMMING_NO_EFFECTS,
    TF_COND_PURGATORY,
    TF_COND_RUNE_KING,
    TF_COND_RUNE_PLAGUE,
    TF_COND_RUNE_SUPERNOVA,
    TF_COND_PLAGUE,
    TF_COND_KING_BUFFED,
    TF_COND_TEAM_GLOWS,
    TF_COND_KNOCKED_INTO_AIR,
    TF_COND_COMPETITIVE_WINNER,
    TF_COND_COMPETITIVE_LOSER,
    TF_COND_HEALING_DEBUFF,
    TF_COND_PASSTIME_PENALTY_DEBUFF,
    TF_COND_GRAPPLED_TO_PLAYER,
    TF_COND_GRAPPLED_BY_PLAYER,
    TF_COND_PARACHUTE_DEPLOYED,
    TF_COND_GAS,
    TF_COND_BURNING_PYRO,
    TF_COND_ROCKETPACK,
    TF_COND_LOST_FOOTING,
    TF_COND_AIR_CURRENT,
    TF_COND_HALLOWEEN_HELL_HEAL,
    TF_COND_POWERUPMODE_DOMINANT,

    TF_COND_LAST
};

/*----------------------------------------------------------------------------*/

enum in_buttons {
    IN_ATTACK    = (1 << 0),
    IN_JUMP      = (1 << 1),
    IN_DUCK      = (1 << 2),
    IN_FORWARD   = (1 << 3),
    IN_BACK      = (1 << 4),
    IN_USE       = (1 << 5),
    IN_CANCEL    = (1 << 6),
    IN_LEFT      = (1 << 7),
    IN_RIGHT     = (1 << 8),
    IN_MOVELEFT  = (1 << 9),
    IN_MOVERIGHT = (1 << 10),
    IN_ATTACK2   = (1 << 11),
    IN_RUN       = (1 << 12),
    IN_RELOAD    = (1 << 13),
    IN_ALT1      = (1 << 14),
    IN_ALT2      = (1 << 15),
    IN_SCORE     = (1 << 16),
    IN_SPEED     = (1 << 17),
    IN_WALK      = (1 << 18),
    IN_ZOOM      = (1 << 19),
    IN_WEAPON1   = (1 << 20),
    IN_WEAPON2   = (1 << 21),
    IN_BULLRUSH  = (1 << 22),
    IN_GRENADE1  = (1 << 23),
    IN_GRENADE2  = (1 << 24),
    IN_ATTACK3   = (1 << 25),
};

#endif /* SDK_ENUMS_H_ */
